BOXPLOT_FIGSIZE = (8, 6)
BOXPLOT_GRID_ALPHA = 0.7

SCATTER_PLOT_FIGSIZE = (10, 6)
SCATTER_PLOT_ALPHA = 0.5
SCATTER_PLOT_GRID_ALPHA = 0.7

HISTOGRAM_FIGSIZE = (10, 6)
HISTOGRAM_ALPHA = 0.75
HISTOGRAM_GRID_ALPHA = 0.7

# Colocar os títulos como constantes também? Melhor não