BOXPLOT_FIGSIZE = (8, 6)
BOXPLOT_GRID_ALPHA = 0.7

SCATTER_PLOT_FIGSIZE = (10, 6)
SCATTER_PLOT_ALPHA = 0.5
SCATTER_PLOT_GRID_ALPHA = 0.7

HISTOGRAM_FIGSIZE = (10, 6)
HISTOGRAM_ALPHA = 0.75
#HISTOGRAM_GRID_ALPHA = 0.7

# MLE
BINOMIAL_FIXED_N = 1000

LINEWIDTH = 2
BINOMIAL_MARKERSIZE = 2
BINOMIAL_ALPHA = 0.5
BINOMIAL_LINEWIDTH = 1

MLE_PLOT_POINT_AMOUNT = 100

# Inferência bayesiana
USE_MLE_AS_REFERENCE_FOR_PRIORS = False