# MLE
BINOMIAL_FIXED_N = 1000

# Gráficos de modelo ajustado por MLE
MLE_PLOT_POINT_AMOUNT = 100

LINEWIDTH = 2
BINOMIAL_MARKERSIZE = 2
BINOMIAL_ALPHA = 0.5
BINOMIAL_LINEWIDTH = 1

# Inferência bayesiana
USE_MLE_AS_REFERENCE_FOR_PRIORS = False